name: Build VSIX
description: Builds the Visual Studio extension package for the solution.

inputs:
  version-number:
    description: >
      If provided, will be used directly as the version of the VSIX. Otherwise, the version will be automatically
      incremented.
    required: false
    default: ''

runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v3.1.0
      with:
        submodules: 'recursive'

    - name: Set VSIX version
      id: vsix-version
      # This PR: https://github.com/timheuer/vsix-version-stamp/pull/4.
      uses: timheuer/vsix-version-stamp@6a9fdb1e261798c5b00449a601b102d9d567c59d
      with:
        manifest-file: Lombiq.Vsix.Orchard\source.extension.vsixmanifest
        vsix-token-source-file: Lombiq.Vsix.Orchard\Constants\ExtensionVersion.cs
        version-number: ${{ inputs.version-number }}

    - shell: pwsh
      run: |
        Write-Output "This is the version: ${{ steps.vsix-version.outputs.version-number }}"

    - name: Add MSBuild to PATH
      # v1.1.3
      uses: microsoft/setup-msbuild@34cfbaee7f672c76950673338facd8a73f637506
      with:
        vs-version: '[17.3,]'

    - name: Build
      shell: pwsh
      run: |
        $buildSwitches = @(
            '-verbosity:minimal'
            '-restore'
            '-property:Configuration=Release'
            '-property:RunAnalyzersDuringBuild=true'
            '-property:TreatWarningsAsErrors=true'
            '-warnaserror'
            '-property:Retries=4'
            '-property:RetryDelayMilliseconds=1000'
            "-property:OutDir=$(Join-Path $PWD artifacts)"
        )

        msbuild @buildSwitches

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Lombiq.Vsix.Orchard.vsix
        path: artifacts/**/*.vsix
