name: Build VSIX
description: Builds the Visual Studio extension package for the solution.

inputs:
  version-number:
    description: >
      If provided, will be used directly as the version of the VSIX. Otherwise, the version will be automatically
      incremented.
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Set VSIX version
      id: vsix-version
      # Latest code as of 17.11.2022.
      uses: timheuer/vsix-version-stamp@9d38292e99e54046455bb68c6a2b5113d269a7d0
      with:
        manifest-file: Lombiq.Vsix.Orchard\source.extension.vsixmanifest
        vsix-token-source-file: Lombiq.Vsix.Orchard\Constants\ExtensionVersion.cs
        version-number: ${{ inputs.version-number }}

    - name: Configure Output Directory
      id: output-directory
      shell: pwsh
      run: |
        "directory=$(Join-Path $PWD artifacts)" >> $Env:GITHUB_OUTPUT

    - name: Build
      uses: Lombiq/GitHub-Actions/.github/actions/msbuild.yml@issue/CARE-265
      with:
        dotnet-build-switches: |
          "-property:OutDir=${{ steps.output-directory.outputs.directory }}"

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: Lombiq.Vsix.Orchard.vsix
        path: artifacts/**/*.vsix
