name: Build

on:
  pull_request:
  push:
    branches:
      - dev

# Mostly buit on https://github.com/timheuer/JwtTools/blob/main/.github/workflows/build.yaml.
jobs:
  build:
    outputs:
      version: ${{ steps.vsix-version.outputs.version-number }}
    name: Build 
    runs-on: windows-latest
    timeout-minutes: 10
    steps:
    - uses: actions/checkout@v3.1.0
      with:
        submodules: 'recursive'

    - name: Increment VSIX version
      id: vsix-version
      # This PR: https://github.com/timheuer/vsix-version-stamp/pull/4.
      uses: timheuer/vsix-version-stamp@6a9fdb1e261798c5b00449a601b102d9d567c59d
      with:
        manifest-file: Lombiq.Vsix.Orchard\source.extension.vsixmanifest
        vsix-token-source-file: Lombiq.Vsix.Orchard\Constants\ExtensionVersion.cs

    - name: Build VSIX
      uses: ./.github/actions/build-vsix
