name: Publish to the Visual Studio Marketplace

on:
  push:
    tags:
      - v*

jobs:
  publish:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3.1.0
      with:
        submodules: 'recursive'

    - name: Build VSIX
      uses: ./.github/actions/build-vsix

    - name: Create Release
      # v1.11.2
      uses: ncipollo/release-action@18eadf9c9b0f226f47f164f5373c6a44f0aae169
      with:
        allowUpdates: true
        generateReleaseNotes: true
        artifacts: artifacts/Lombiq Orchard Visual Studio Extension.vsix

    - name: Publish to Marketplace
      # v0.2
      uses: cezarypiatek/VsixPublisherAction@759bd2ec02ac1b13dea56d8c84834e517278b5b1
      with:
        extension-file: 'artifacts\Lombiq Orchard Visual Studio Extension.vsix'
        publish-manifest-file: 'Marketplace\publishManifest.json'
        personal-access-code: nonsense
